<div class="main-container">
    <div class="main-content">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="login-container">
                    <div class="center">
                        <h1>
                            <i class="ace-icon fa fa-leaf green"></i>
                            <span class="red">Clean blog</span>

                        </h1>
                        <h4 class="blue" id="id-company-text">Registration</h4>
                    </div>

                    <div class="space-6"></div>

                    <div class="position-relative">
                        <div id="signup-box" class="signup-box widget-box no-border">
                            <div class="widget-body">
                                <div class="widget-main">
                                    <h4 class="header green lighter bigger">
                                        <i class="ace-icon fa fa-users blue"></i>
                                        New User Registration
                                    </h4>

                                    <div class="space-6"></div>
                                    <p> Enter your details to begin: </p>

                                    <?php if (!empty($this->message)): ?>

                                        <p><?php print $this->message; ?></p>

                                    <?php endif; ?>
                                    <?php print $this->form; ?>


                                </div>

                                <div class="toolbar center">
                                    <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index'), NULL, true); ?>" data-target="#login-box" class="back-to-login-link">
                                        <i class="ace-icon fa fa-arrow-left"></i>
                                        Back to login
                                    </a>
                                </div>
                            </div><!-- /.widget-body -->
                        </div><!-- /.signup-box -->
                    </div><!-- /.position-relative -->
                </div>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.main-content -->
</div><!-- /.main-container -->