<div class="content-box-large">
    <div class="panel-body">
        <p>Are u sure u want to delete article:
            '<?php echo $this->escape($this->articles['subject']); ?>' ?
        </p>
        <form action="<?php echo $this->url(array('action' => 'deletearticles')); ?>" method="post">
            <div>
                <input type="hidden" name="id" value="<?php echo $this->articles['id']; ?>" />
                <input type="submit" name="del" value="Yes" />
                <input type="submit" name="del" value="No" />
            </div>
        </form>
    </div>
</div>
