<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Zend CMS Admin Panel</title>

        <link href="<?php echo $this->baseUrl(); ?>/assets/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl(); ?>/assets/font-awesome/4.5.0/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl(); ?>/assets/css/fonts.googleapis.com.css" media="screen" rel="stylesheet" type="text/css" />

        <link href="<?php echo $this->baseUrl(); ?>/assets/css/ace.min.css" media="screen" rel="stylesheet" type="text/css" class="ace-main-stylesheet" id="main-ace-style" />

        <link href="<?php echo $this->baseUrl(); ?>/assets/css/ace-skins.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl(); ?>/assets/css/ace-rtl.min.css" media="screen" rel="stylesheet" type="text/css" />


        <script src="<?php echo $this->baseUrl(); ?>/assets/js/ace-extra.min.js" type="text/javascript"></script>

        <script src="<?php echo $this->baseUrl(); ?>/assets/js/ace.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/js/ace-elements.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/js/jquery-2.1.4.min.js" type="text/javascript"></script>

        <?php $this->headScript()->appendFile('//cdn.ckeditor.com/4.6.2/standard/ckeditor.js'); ?>
        <?php echo $this->headScript() ?>

        <script type="text/javascript">
            if ('ontouchstart' in document.documentElement)
                document.write("<script src='assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
        </script>

    </head>

    <body>



        <?php echo $this->placeholder('menu'); ?>


        <div class="main-container ace-save-state" id="main-container">
            <script type="text/javascript">
                try {
                    ace.settings.loadState('main-container')
                } catch (e) {
                }
            </script>

            <div id="sidebar" class="sidebar                  responsive                    ace-save-state">
                <script type="text/javascript">
                    try {
                        ace.settings.loadState('sidebar')
                    } catch (e) {
                    }
                </script>



                <ul class="nav nav-list">

                    <li class="current"><a href="<?php echo $this->url(array('controller' => 'administration', 'action' => 'index'), NULL, true); ?>">
                            <i class="menu-icon fa fa-tachometer"></i>
                            <span class="menu-text"> Dashboard </span>
                        </a></li>


                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'administration', 'action' => 'listusers'), NULL, true); ?>"> <i class="menu-icon fa fa-users
                                                                                                                                              "></i> Users</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'administration', 'action' => 'listarticles'), NULL, true); ?>"> <i class="menu-icon fa fa-list"></i> Articles</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'administration', 'action' => 'listmessages'), NULL, true); ?>"> <i class="menu-icon fa fa-envelope-o"></i> Messages</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'administration', 'action' => 'listcomments'), NULL, true); ?>"> <i class="menu-icon fa fa-envelope-o"></i> Comments</a>
                    </li>

                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'administration', 'action' => 'addcategories'), NULL, true); ?>"><i class="menu-icon fa fa-pencil-square-o"></i> New category</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'administration', 'action' => 'addarticles'), NULL, true); ?>"> <i class="menu-icon fa fa-pencil-square-o"></i> New article</a>
                    </li>
                    <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout'), NULL, true); ?>"><i class="menu-icon fa fa-power-off"></i>
                            Log out</a></li>
                </ul><!-- /.nav-list -->

                <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
                    <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
                </div>
            </div>

            <div class="main-content">
                <div class="main-content-inner">
                    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                        <ul class="breadcrumb">
                            <li>
                                <i class="ace-icon fa fa-home home-icon"></i>
                                <a href="#">Home</a>
                            </li>


                            <li class="active">Blank Page</li>
                        </ul><!-- /.breadcrumb -->

                        <div class="nav-search" id="nav-search">
                            <form class="form-search">
                                <span class="input-icon">
                                    <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                                    <i class="ace-icon fa fa-search nav-search-icon"></i>
                                </span>
                            </form>
                        </div><!-- /.nav-search -->
                    </div>

                    <div class="page-content">


                        <div class="row">
                            <div class="col-xs-12">
                                <!-- PAGE CONTENT BEGINS -->




                                <?php echo $this->layout()->content; ?>







                                <!-- PAGE CONTENT ENDS -->
                            </div><!-- /.col -->
                        </div><!-- /.row -->
                    </div><!-- /.page-content -->
                </div>
            </div><!-- /.main-content -->



            <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
                <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
            </a>
        </div><!-- /.main-container -->


        <?php echo $this->placeholder('footer'); ?>

    </body>

</html>
