<!DOCTYPE html>
<html>

    <head>
        <title>Zend Commerce Login/Registration</title>


        <link href="<?php echo $this->baseUrl(); ?>/assets/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl(); ?>/assets/css/fonts.googleapis.com.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl(); ?>/assets/font-awesome/4.5.0/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl(); ?>/assets/css/ace.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl(); ?>/assets/css/ace-rtl.min.css" media="screen" rel="stylesheet" type="text/css" />

        <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

    </head>

    <body>

        <?php echo $this->layout()->content; ?>

    </body>

</html>
